version: '3'

services:
  # Сервис для PHP с FPM
  php:
    build:
      context: .
    volumes:
      - ./src:/var/www/html
    networks:
      - app-network

  # Сервис для nginx
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mariadb
    networks:
      - app-network

  # Сервис для MariaDB
  mariadb:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - app-network

  # Сервис для Redis
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mariadb_data:
    driver: local
